// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type Carrier struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
}

type CarrierRegion struct {
	ID                    uuid.UUID
	CarrierID             uuid.UUID
	RegionID              uuid.UUID
	EstimatedDeliveryDays int32
	PricePerKg            string
	CreatedAt             sql.NullTime
}

type Package struct {
	ID                uuid.UUID
	TrackingCode      string
	Product           string
	WeightKg          float64
	DestinationState  string
	Status            string
	HiredCarrierID    uuid.NullUUID
	HiredPrice        sql.NullString
	HiredDeliveryDays sql.NullInt32
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type Region struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
}

type State struct {
	Code      string
	Name      string
	RegionID  uuid.UUID
	CreatedAt sql.NullTime
}
