// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error)
	DeletePackage(ctx context.Context, id uuid.UUID) error
	GetCarrierById(ctx context.Context, id uuid.UUID) (Carrier, error)
	GetCarrierRegions(ctx context.Context, carrierID uuid.UUID) ([]GetCarrierRegionsRow, error)
	GetPackageById(ctx context.Context, id uuid.UUID) (Package, error)
	GetPackageByTrackingCode(ctx context.Context, trackingCode sql.NullString) (Package, error)
	GetQuotesForPackage(ctx context.Context, arg GetQuotesForPackageParams) ([]GetQuotesForPackageRow, error)
	GetRegionByState(ctx context.Context, code string) (GetRegionByStateRow, error)
	GetStateByCode(ctx context.Context, code string) (GetStateByCodeRow, error)
	HireCarrier(ctx context.Context, arg HireCarrierParams) error
	ListCarriers(ctx context.Context) ([]Carrier, error)
	ListPackages(ctx context.Context) ([]Package, error)
	ListRegions(ctx context.Context) ([]Region, error)
	ListStates(ctx context.Context) ([]ListStatesRow, error)
	TrackingCodeExists(ctx context.Context, trackingCode sql.NullString) (bool, error)
	UpdatePackageStatus(ctx context.Context, arg UpdatePackageStatusParams) error
	UpdatePackageStatusWithTracking(ctx context.Context, arg UpdatePackageStatusWithTrackingParams) error
}

var _ Querier = (*Queries)(nil)
