services:
  psql:
    hostname: "primary"
    image: postgres:latest
    container_name: olist-db
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - POSTGRES_DB=olist-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ROOT_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    volumes:
      - type: bind
        source: ../../db/migrations
        target: /migrations
    command: [ "-path", "/migrations", "-database", "postgres://postgres:postgres@psql:5432/olist-db?sslmode=disable", "up" ]
    depends_on:
      psql:
        condition: service_healthy

volumes:
  db: